name: docToolchain Build & Deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 1. Repo auschecken
      - name: Checkout
        uses: actions/checkout@v4

      # 2. docToolchain im Docker-Container ausfÃ¼hren
      - name: Build docs
        run: |
          chmod +x dtcw
          ./dtcw docker generateHTML

      # 3. Rename arc42.html > index.html
      - name: Create index.html redirect
        run: |
          echo '<meta http-equiv="refresh" content="0; url=arc42.html">' > build/html5/index.html

      # 4. Export dsl to puml
      - name: Build docs
        run: |
          chmod +x dtcw
          ./dtcw docker exportStructurizr
          ./dtcw docker generateHTML

      # 5. Build-Output auf gh-pages deployen
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/html5